name: Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please fill out the sections below.

  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: What happened?
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain the problem.

  - type: dropdown
    id: area
    attributes:
      label: Area
      description: Which part of the application is affected?
      options:
        - Leaderboard
        - Creator Profile
        - Stock Page
        - Search
        - Tip Detail
        - Admin Dashboard
        - API
        - Scoring Algorithm
        - Scraper
        - Parser
        - Other
    validations:
      required: true

  - type: input
    id: environment
    attributes:
      label: Environment
      description: "e.g., Node 20.x, Chrome 120, macOS 14"
      placeholder: "Node version, browser, OS"
