name: Feature Request
description: Suggest a new feature or improvement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please describe it below.

  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What problem does this feature solve? What's missing today?
      placeholder: "I'm frustrated when..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: Describe the solution you'd like.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Any alternative solutions or features you've considered?

  - type: dropdown
    id: area
    attributes:
      label: Area
      description: Which part of the application would this affect?
      options:
        - Leaderboard
        - Creator Profiles
        - Scoring Algorithm
        - Scraping Engine
        - NLP Parser
        - Market Data
        - Admin Dashboard
        - API
        - SEO / Social Sharing
        - New Data Source
        - Other
    validations:
      required: true

  - type: dropdown
    id: willingness
    attributes:
      label: Contribution
      description: Would you be willing to work on this?
      options:
        - "Yes, I'd like to implement this"
        - "I can help but need guidance"
        - "No, just suggesting"
    validations:
      required: true
